FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Code/PullReqTest.Api/PullReqTest.Api.csproj", "Code/PullReqTest.Api/"]
COPY ["Code/PullReqTest.Business/PullReqTest.Business.csproj", "Code/PullReqTest.Business/"]
COPY ["Code/PullReqTest.Data/PullReqTest.Data.csproj", "Code/PullReqTest.Data/"]
COPY ["Code/PullReqTest.Entities/PullReqTest.Entities.csproj", "Code/PullReqTest.Entities/"]
COPY ["Code/PullReqTest.Test.Api/PullReqTest.Test.Api.csproj", "Code/PullReqTest.Test.Api/"]
COPY ["Code/PullReqTest.Test.Business/PullReqTest.Test.Business.csproj", "Code/PullReqTest.Test.Business/"]
RUN dotnet restore "Code/PullReqTest.Api/PullReqTest.Api.csproj"
COPY . .
WORKDIR "/src/Code/PullReqTest.Api"
RUN dotnet build "PullReqTest.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PullReqTest.Api.csproj" -c Release -o /app/publish

WORKDIR /src
RUN dotnet test --results-directory /testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/testresults/coverage/ /p:MergeWith=/testresults/coverage/coverage.json "Code/PullReqTest.Test.Api/PullReqTest.Test.Api.csproj"
RUN dotnet test --results-directory /testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/testresults/coverage/ /p:MergeWith=/testresults/coverage/coverage.json "Code/PullReqTest.Test.Business/PullReqTest.Test.Business.csproj"
