name: A123a.tyGK_1
'on':
  push:
    branches:
      - main
    paths:
      - '**/testttttttpy/**'
env:
  DOCKER_BUILD_FILE_PATH: ./testttttttpy/Dockerfile.build
  DOCKER_FILE_PATH: ./testttttttpy/Dockerfile.publish
  DOCKER_BUILD_CONTEXT: testttttttpy
  DOCKER_PUBLISH_CONTEXT: testttttttpy
  CONTAINER_NAME: b123a.ty_1
  REPOSITORY_NAME: b123a.ty_1
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build and Test
        run: docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_BUILD_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:ojiugytfdfghuijghcfxvc
      - name: Runs docker
        run: docker run --name ${{ env.CONTAINER_NAME }} -d ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:ojiugytfdfghuijghcfxvc
      - name: copy build files
        run: |-
          docker cp ${{ env.CONTAINER_NAME }}:/app/kmhjgfd/ ./${{ env.DOCKER_PUBLISH_CONTEXT }}
          docker stop ${{ env.CONTAINER_NAME }}
          docker rm ${{ env.CONTAINER_NAME }}
      - name: Build and  push image to container registry
        run: |-
          docker build ${{ env.DOCKER_PUBLISH_CONTEXT }} -f ${{ env.DOCKER_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:ojiugytfdfghuijghcfxvc
          docker push ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:ojiugytfdfghuijghcfxvc
